version: 0.1.1

environment:
  matrix:
    - QTDIR: C:\Qt\5.5\msvc2013

configuration: Release

install:
  - choco install -y graphviz
  - set PATH=%PATH%;%QTDIR%\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;C:\Qt\5.5\msvc2013\bin;C:\Qt\Tools\QtCreator\bin

build_script:
  - qmake.exe KLang.pro -r -spec win32-msvc2013
  - VcVars32
  - jom
  - windeployqt --no-system-d3d-compiler --no-translations release
  - jom install

artifacts:
  - path: release
    name: KLang-$(APPVEYOR_BUILD_VERSION)
    type: zip

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: f1qLXI72FZwkMS6SHE+dBvV4N9t3AZzUOpxexMXs2h79b3mVqTgZ/1Mw3x/L+rSj
  artifact: KLang-$(APPVEYOR_BUILD_VERSION)
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
