version: 0.3.5-{build}

environment:
  matrix:
    - QTDIR: C:\Qt\5.5\msvc2013

configuration: Release

install:
  - choco install -y graphviz
  - set PATH=%PATH%;%QTDIR%\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;C:\Qt\5.5\msvc2013\bin;C:\Qt\Tools\QtCreator\bin

build_script:
  - qmake.exe KLang.pro -r -spec win32-msvc2013
  - VcVars32
  - jom
  - windeployqt --no-system-d3d-compiler --no-translations KLangIDE\release\package
  - qmake.exe KLang.pro -r -spec win32-msvc2013 #run configuration one more time after klang.dll exist
  - jom install
  - jom check

artifacts:
  - path: KLangIDE\release\package
    name: KLang-$(APPVEYOR_BUILD_VERSION)_win_x86_32
    type: zip

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: f1qLXI72FZwkMS6SHE+dBvV4N9t3AZzUOpxexMXs2h79b3mVqTgZ/1Mw3x/L+rSj
  artifact: KLang-$(APPVEYOR_BUILD_VERSION)_win_x86_32
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
