environment:
  matrix:
    - QTDIR: C:\Qt\5.5\msvc2013

configuration: Release

install:
  - choco install -y graphviz
  - set PATH=%PATH%;%QTDIR%\bin;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin;C:\Qt\5.5\msvc2013\bin;C:\Qt\Tools\QtCreator\bin

build_script:
  - qmake.exe KLang.pro -r -spec win32-msvc2013
  - VcVars32
  - jom
  - windeployqt --no-system-d3d-compiler --no-translations release
  - jom install

artifacts:
  - name: KLang
    path: release
    type: zip
